name: UnitTests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Install dependancies
        run: |
          python -m venv .venv  
          source .venv/bin/activate
          pip install -r requirements.txt

        
      - name: Run Tests
        run: |
          source .venv/bin/activate
          python -m unittest discover -s tests -p "*.py"
